theseus-root = "../theseus"

[build-cells]
cargo-target = "../rust/x86_64-theseus.json"
cargo-target-name = "x86_64-theseus"
toolchain = "theseus"

[copy-crate-objects]
extra-target-dirs = [ "../rust/build/x86_64-unknown-linux-gnu/stage2-std" ]

[add-bootloader]
bootloader = "limine"