arch = "x86_64"
theseus-root = "."
build-dir = "./build"
discover = []
output-iso = "{build-dir}/theseus-{arch}.iso"
linker = "ld"
stripper = "strip"
target-name = "{arch}-theseus"
target = "{directories.cfg}/{target-name}.json"
build-mode = "release"
nanocore-bin = "nano_core-{arch}.bin"
nanocore-path = "{directories.nanocore}/{nanocore-bin}"

[prefixes]
kernel = "k#"
applications = "a#"
executables = "e#"

[directories]
kernel = "{theseus-root}/kernel"
apps = "{theseus-root}/applications"
cfg = "{theseus-root}/cfg"
nanocore = "{build-dir}/nano_core"
isofiles = "{build-dir}/isofiles"
boot = "{directories.isofiles}/boot"
modules = "{directories.isofiles}/modules"
deps = "{build-dir}/deps"
target = "{build-dir}/target"
extracted-rlibs = "{build-dir}/extracted_rlibs"
debug-symbols = "{build-dir}/debug_symbols"
sysroot = "{directories.deps}/sysroot/lib/rustlib/{target-name}/lib"
target-deps = "{directories.target}/{target-name}/{build-mode}/deps"

[build-cells]
manifest-path = "{theseus-root}/kernel/nano_core/Cargo.toml"
cargo = "cargo"
cargo-flags = []
rust-flags = []

[link-nanocore]
static-lib-path = "{directories.target}/{target-name}/{build-mode}/libnano_core.a"
asm-sources-dir = "{theseus-root}/kernel/nano_core/src/boot/arch_{arch}"
linker-script-path = "{link-nanocore.asm-sources-dir}/linker_higher_half.ld"
linker = "{linker}"

[serialize-nanocore-syms]
output-path = "{directories.modules}/{prefixes.kernel}nano_core.serde"
readelf = "readelf"

[relink-rlibs]
linker = "{linker}"
remove-rlibs-dirs = true

[copy-crate-objects]
target-dirs = [ "{directories.target-deps}" ]
extra-apps = [ "libtheseus" ]
debug-crate-objects = false

[relink-objects]
partial-relinking-script = "{directories.cfg}/partial_linking_combine_sections.ld"
linker = "{linker}"
stripper = "{stripper}"

[strip-objects]
stripper = "{stripper}"
strip-nanocore = true

[add-bootloader]
nanocore-destination = "{directories.boot}/kernel.bin"
bootloader = "grub"
grub-mkrescue = "grub-mkrescue"
limine-config = "built-in"
limine-commit = "3f6a3303434d07e4663544d35fc0beb1b7c26364"
limine-tarball = "https://github.com/limine-bootloader/limine/archive/{add-bootloader.limine-commit}.tar.gz"
limine-subdir = "limine-{add-bootloader.limine-commit}"
tarball-path = "{add-bootloader.extract-dir}.tar.gz"
extract-dir = "{build-dir}/limine-prebuilt"
expected-subdir = "{add-bootloader.extract-dir}/{add-bootloader.limine-subdir}"
downloader = "wget"
xorriso = "xorriso"
