cargo = "cargo"
arch = "x86_64"
theseus-root = "."
build-dir = "build"
discover = []

[prefixes]
kernel = "k#"
applications = "a#"
executables = "e#"

[build-cells]
# relative to theseus-root
cargo-target = "../rust/x86_64-theseus.json"
cargo-target-name = "x86_64-theseus"
build-mode = "release"
other-cargo-flags = []
other-rust-flags = []
# build-std = ["core", "alloc"]
build-std = []
build-std-features = ["compiler-builtins-mem"]

[link-nano-core]
linker = "ld"

[serialize-nano-core-syms]
readelf = "readelf"

[relink-rlibs]
linker = "ld"
remove-rlibs-dirs = true

[copy-crate-objects]
extra-target-dirs = [ ]
extra-apps = [ "libtheseus" ]
debug-crate-objects = false

[relink-objects]
linker = "ld"
stripper = "strip"

[strip-objects]
stripper = "strip"
strip-nano_core = true

[add-bootloader]
bootloader = "grub"
grub-mkrescue = "grub-mkrescue"
limine-config = "built-in"
limine-tarball = "https://github.com/limine-bootloader/limine/archive/3f6a3303434d07e4663544d35fc0beb1b7c26364.tar.gz"
limine-subdir = "limine-3f6a3303434d07e4663544d35fc0beb1b7c26364"
downloader = "wget"
xorriso = "xorriso"
